### ISSUE TITLE
br on ssh hangs indefinitely on large multi dir / multi project NVMe SSD

### ISSUE THREAD

**Issue by drahnr** [Canop/broot#294] opened 2020-10-21 10:12 UTC
**Describe the bug**
`br` freezes on first letter when used via `ssh`, local usage works fine.

**To Reproduce**

1. `ssh localhost` (only tested with actual remote machines)
1. `mkdir -p parity/polkadot; cd parity`
1. `git clone https://github.com/paritytech/polkadot`
1. `cd ..`
2. `br`
3. <kbd>p</kbd>
No more input is accepted, cannot send `br` to the background via <kbd>CTRL</kbd> + <kbd>Z</kbd>, can only terminate the terminal tab.

**Expected behavior**
no hang

**Screenshots**
![image](https://user-images.githubusercontent.com/667047/96706241-9e7dd180-1396-11eb-8f56-07d2bb8031c7.png)

**Configuration (please complete the following information):**
 - OS: [e.g. iOS] Fedora 
 - Version [e.g. 22] broot 1.0.3

**Additional context**

**Comment by Canop** [comment] 2020-10-21 10:31
Unless I'm wrong, this has no link to ssh: broot just seems to hang on your server.

Is there a slow volume mounted somewhere in the visible tree ?

**Comment by drahnr** [comment] 2020-10-21 11:55
> Unless I'm wrong, this has no link to ssh: broot just seems to hang on your server.

Included for sake of completeness.
 
> Is there a slow volume mounted somewhere in the visible tree ?

It's all one one zstd compressed btrfs subvolume residing on a PCIe v3 NVMe SSD. There are no other partitions mounted under that subtree.

**Comment by drahnr** [comment] 2020-10-22 07:47
Annex: I did an update from a roughly 4 months old version (which worked flawlessly) to `1.0.3`, which exhibits this behaviour.

**Comment by Canop** [comment] 2020-10-22 07:53
Just to be sure I don't misunderstand you: a version from 4 months ago (0.14 maybe?) did work, and the current one blocks ?

This is interesting. Can you give me the [debug log](https://dystroy.org/broot/community/#log) of broot failing ?

**Comment by drahnr** [comment] 2020-10-22 07:55
Just verified that `0.19.4` works as anticipated.

**Comment by drahnr** [comment] 2020-10-22 07:59
```
07:58:35 [ INFO] Starting Broot v1.0.3 with log level DEBUG
07:58:35 [DEBUG] (1) broot::git::ignore: GitIgnoreFile::new took 2.304µs
07:58:35 [DEBUG] (1) broot::tree_build::builder: GitIgnorer::default took 142.277µs
07:58:35 [DEBUG] (1) broot::app::app: display panel took 288.02µs
07:58:36 [DEBUG] (1) broot::app::app: event: Key(KeyEvent { code: Char('p'), modifiers: NONE })
07:58:36 [DEBUG] (1) broot::app::app: command after add_event: PatternEdit { raw: "p", expr: BeTree { atoms: [PatternParts { parts: ["p"] }], nodes: 
[Node { operator: None, parent: None, left: Atom(0), right: None, unary: false }], head: 0, tail: 0, last_pushed: Atom, op_count: 0, openess: 0 } }
07:58:36 [DEBUG] (1) broot::app::panel: result in panel PanelId(0): Ok(Keep)
07:58:36 [DEBUG] (1) broot::app::app: display panel took 244.037µs
07:58:36 [DEBUG] (1) broot::tree_build::builder: GitIgnorer::default took 321ns
```

Note that it never terminates, but I have to kill it.

**Comment by drahnr** [comment] 2020-10-22 08:06
Just verified that 0.20.3 works as anticipated as well.

**Comment by Canop** [comment] 2020-10-22 08:06
Thanks a lot for this test, this reduces the diff a lot!

**Comment by Canop** [comment] 2020-10-22 08:12
Can you find the first failing version ?

**Comment by drahnr** [comment] 2020-10-22 08:14
I just did, `1.0.0` works, `1.0.1` fails.

**Comment by Canop** [comment] 2020-10-22 08:15
Ok, so that leaves me with this: https://github.com/Canop/broot/compare/v1.0.0...v1.0.1

**Comment by drahnr** [comment] 2020-10-22 08:22
Could you create a branch with `log::trace` extra logging (plenty!) to obtain some information on what's going on, otherwise this has to wait until later today/tomorrow when I can do some remote debugging.

**Comment by Canop** [comment] 2020-10-22 08:25
I'll try to prepare something but I'm at work right now, so this may take a while (especially as I leave for holidays in 2 days). 

If you prefer you're welcome in the chat: https://miaou.dystroy.org/3490

**Comment by Canop** [comment] 2020-10-22 08:41
Among the suspects: a cyclic symlinks chain : https://github.com/Canop/broot/compare/v1.0.0...v1.0.1#diff-054348a10e99258e50c67a4727e6add50481b2bf1a02fec8c90176a9306ee7afR39-R44
This could easily be fixed with a counter

**Comment by drahnr** [comment] 2020-10-22 08:44
That link is borked :zap:

**Comment by Canop** [comment] 2020-10-22 08:46
> That link is unfortunately borked

here: https://github.com/Canop/broot/blob/master/src/tree/tree_line_type.rs#L39

This stupid loop was introduced in this release

**Comment by Canop** [comment] 2020-10-22 08:52
I can reproduce a freeze with just

![image](https://user-images.githubusercontent.com/617006/96848415-b4ea6280-1454-11eb-94b6-d477cca4613f.png)

I'll fix that and see if it's also the problem you saw

**Comment by Canop** [comment] 2020-10-22 09:02
Works better now:

![image](https://user-images.githubusercontent.com/617006/96849372-d39d2900-1455-11eb-8398-31a6e741a590.png)

@drahnr I just pushed the issue_294 branch. Can you test it ?

**Comment by Canop** [comment] 2020-10-22 10:28
I've merged it into master but I'd like confirmation this was really your problem

**Comment by drahnr** [comment] 2020-10-22 10:39
I can confirm master @ 64956e00 resolves the issue :tada:

**Comment by Canop** [comment] 2020-10-22 10:41
Thanks for the help!

I didn't want to wrap a new release before going in holiday but I think I'll do it in a few hours because this bug is really nasty.

**Closed** 2020-10-22 15:38 UTC

**Comment by Canop** [comment] 2020-10-22 15:45
Version 1.0.4 has the fix
