### ISSUE TITLE
MacOs: alt-enter doesn't work for everybody (define another combination?)

### ISSUE THREAD

**Issue by Canop** [Canop/broot#86] opened 2020-01-09 12:13 UTC
alt-enter on mac seems to do the same than enter.

If some people are able to test on Mac, please tell me and watch this issue so that I can let you test before official release.

**Please people also check the version of broot you have is at least 0.11.3. I suspect some obsolete brew formula is still around.**

--------------------

Please note that you always can remap yourself to another key combination:

```toml
[[verbs]]
key = "ctrl-o"
execution = ":open_leave"
```

**Comment by Etheryte** [comment] 2020-01-09 13:14
Running the Homebrew installation on macOS Mojave, <kbd>alt</kbd><kbd>enter</kbd> performs the same action as just <kbd>enter</kbd>. Using `:cd` works as expected.

**Comment by mirosval** [comment] 2020-01-09 13:18
@Etheryte I think the Homebrew version is `0.10.3`, it seems that there have been versions released that fix the `alt-enter`

**Comment by okomarov** [comment] 2020-01-09 13:18
Same on macOS Catalina, installed with Cargo.

**Comment by mirosval** [comment] 2020-01-09 13:23
`alt-enter` works for me on Catalina and zsh, built from Cargo

**Comment by okomarov** [comment] 2020-01-09 13:28
@mirosval It quits `br` and `cd`'s into the directory? Mine just focuses, i.e. displayes the content of the searched directory inside `br`.

**Comment by Canop** [comment] 2020-01-09 13:29
@okomarov  the behavior you describe is the one of enter not alt-enter. I guess the alt-enter combination isn't properly recognized by broot on your system.

**Comment by atoav** [comment] 2020-01-09 13:36
On Windows (e.g. CMD using the WSL Ubuntu) the key combination <kbd>Alt</kbd>+<kbd>Enter</kbd> is used for entering Fullscreen...

**Comment by okomarov** [comment] 2020-01-09 13:40
> @okomarov the behavior you describe is the one of enter not alt-enter. I guess the alt-enter combination isn't properly recognized by broot on your system.

Yes, I was confirming that <kbd>alt</kbd> + <kbd>enter</kbd> is not mapping to `:cd`.

**Comment by rahulnair23** [comment] 2020-01-09 16:33
`option` + `enter` on MacOS Terminal and iTerm need to be set up by users to work properly. Setting it to output `Esc+Enter` worked for me on iTerm2.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/1908664/72085636-8e13d300-32fd-11ea-9052-2fcd6c1582b0.png">

**Comment by masukomi** [comment] 2020-01-09 16:38
hitting `option`+`enter` in iTerm2  with a folder selected (i've probably already done what @rahulnair23 suggested)  did CD me but also resulted in 

```
New Configuration file written in "/Users/masukomi/Library/Preferences/org.dystroy.broot/conf.toml".
You should have a look at it.
```

which is NOT expected (or relevant) behavior for a new user to see. It comes across as a bug. "WTF?! a config file?! I was trying to CD?"

**Comment by Canop** [comment] 2020-01-09 18:17
I've had confirmation the problem is still present with 0.11.4.

**Comment by Canop** [comment] 2020-01-09 18:19
People having this problem can you please follow this procedure:

1. start broot with `BROOT_LOG=debug broot`
2. select a directory then do alt-enter
3. copy what's inside the dev.log file and post it here, along with your OS version, terminal name and broot version

?

**Comment by mirosval** [comment] 2020-01-09 18:30
@okomarov @Canop I'm using Alacritty there it works (`cd`s into the directory and exits), I can confirm it doesn't work in iTerm (does the same as plain enter)

**Comment by Canop** [comment] 2020-01-09 18:31
@mirosval can you please try [this](https://github.com/Canop/broot/issues/86#issuecomment-572687681) in iTerm so that I can see whether something can be detected (and maybe work on the problem with the authors of crossterm) ?

**Comment by mirosval** [comment] 2020-01-09 18:41
Relevant section for iTerm:
```
  62   │ 18:35:16 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Down, modifiers: (empty) })
  63   │ 18:35:16 [DEBUG] (1) broot::app: action: VerbIndex(10)
  64   │ 18:35:17 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Down, modifiers: (empty) })
  65   │ 18:35:17 [DEBUG] (1) broot::app: action: VerbIndex(10)
  66   │ 18:35:17 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Enter, modifiers: (empty) })
  67   │ 18:35:17 [DEBUG] (1) broot::app: action: OpenSelection
```

Same in Alacritty:

```  24   │ 18:39:16 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Down, modifiers: (empty) })
  25   │ 18:39:16 [DEBUG] (1) broot::app: action: VerbIndex(10)
  26   │ 18:39:17 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Down, modifiers: (empty) })
  27   │ 18:39:17 [DEBUG] (1) broot::app: action: VerbIndex(10)
  28   │ 18:39:18 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Enter, modifiers: ALT })
  29   │ 18:39:18 [DEBUG] (1) broot::app: action: AltOpenSelection
  30   │ 18:39:18 [DEBUG] (1) broot::app: cmd result quit
  31   │ 18:39:18 [DEBUG] (1) broot::app: we left the screen
  32   │ 18:39:18 [ INFO] bye
```

**Comment by ghuls** [comment] 2020-01-09 18:59
> > @okomarov the behavior you describe is the one of enter not alt-enter. I guess the alt-enter combination isn't properly recognized by broot on your system.
> 
> Yes, I was confirming that alt + enter is not mapping to `:cd`.

In `Alacritty` terminal `alt` + `enter` also  toggles full screen mode of the terminal by default. Maybe `shift` + `enter` is a better default combination.

**Comment by Canop** [comment] 2020-01-09 19:03
@ghuls  I'm not sure the shift-enter combination can be detected on iTerm or Alacrity. I can't detect it on linux terminals.

You can see what combination was detected by launching broot with `BROOT_LOG=debug br` (and for example opening the log in another terminal with `tail -f dev.log`)

**Comment by nl-brett-stime** [comment] 2020-01-09 21:58
@Canop I get the following from iTerm2:

`21:56:10 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Enter, modifiers: (empty) })`

I was holding down the Alt key so I'm not sure how to go about convincing OSX and/or iTerm to actually include it in the modifiers.

**Comment by nl-brett-stime** [comment] 2020-01-09 22:05
Sorry. I see mirosval already posted that. Shift+Enter is the same:

```
22:04:36 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Enter, modifiers: (empty) })
```

**Comment by nl-brett-stime** [comment] 2020-01-09 22:28
Looks like the key events are coming from the crossterm lib.

We might need to hook into and log e.g., the `could_not_parse_event_error`s being raised in https://github.com/crossterm-rs/crossterm/blob/71029c4a8719ce08a2fa487d9403610ec48acf42/src/event/sys/unix/parse.rs to capture the exact bytes that e.g., iTerm2 is sending.

That lib might also end up needing some code specifically for OSX and/or iTerm. Right now it doesn't look any OSX terminals are part of their test suite.

In the mean time, we can work around by setting ESC+ per https://github.com/Canop/broot/issues/86#issuecomment-572641935

**Comment by TimonPost** [comment] 2020-01-10 07:48
It is difficult to support all key codes all systems and all terminals. This isn't quite universal. And there are a lot of edge cases. An ANSI code parsing layer is in the making. The plan is that Crossterm will use this library for parsing. Have a look over at https://github.com/crossterm-rs/crossterm/pull/330

**Comment by nl-brett-stime** [comment] 2020-01-10 15:13
@TimonPost: Yeah, the difficulty of supporting a fragmented ecosystem makes sense. To whatever degree crossterm can facilitate opt-in, byte-level logging; people will be enabled to capture the mappings from their own system. Then, hopefully, some number of the crowd will end up pushing their findings back upstream.

**Comment by zachvalenta** [comment] 2020-01-10 20:41
`alt-enter` was working for me (Mojave, broot version 0.10.3) earlier today but now I get the error message `This feature needs broot to be launched with the br script`

**Comment by Canop** [comment] 2020-01-10 21:11
@zachvalenta  It means it works, but that for alt-enter to be usable you need to use `br` to launch br.
(related: https://github.com/Canop/broot/issues/115 )

**Comment by zachvalenta** [comment] 2020-01-10 22:05
> @zachvalenta It means it works, but that for alt-enter to be usable you need to use `br` to launch br.

Aha, now I understand the error message, cheers.

I'm not sure on the cause of the error, however, because I afaik I'm sourcing the `br` script in my `.bashrc` (https://github.com/zachvalenta/dotfiles/blob/master/.bashrc#L9).

**Comment by satotake** [comment] 2020-01-11 10:44
I faced the same issue.
But it was fixed by `broot --install` .
(installed via homebrew)

**Comment by zachvalenta** [comment] 2020-01-11 17:24
> I faced the same issue.
> But it was fixed by `broot --install` .
> (installed via homebrew)

Good idea, although when I run that I get:

```
/u/l/bin $ broot --install
.bashrc already patched, no change made.
.zshrc already patched, no change made.
No shell config found, we can't install the br function.
We were looking for the following file(s):
• "/Users/zach/.config/fish/config.fish"
```

**Comment by jvolkman** [comment] 2020-01-14 22:12
In the default Terminal.app, enabling the "Use Option as Meta Key" works (for me).

![Screen Shot 2020-01-14 at 2 09 14 PM](https://user-images.githubusercontent.com/124501/72387214-d9502c00-36d7-11ea-9264-67c5c6bdf8b6.png)

**Comment by NickyWeber** [comment] 2020-01-16 09:10
Is there a workaround by defining another key for cd-ing in to the selected directory on MacOS? I tried something like 
```
[[verbs]]
key = "ctrl-f"
execution = "cd {directory}"
```
But it will just quit broot and stay in the current directory. 
I am using **iTerm2**.

**Comment by Canop** [comment] 2020-01-16 09:16
@NickyWeber A `cd` must be done on the parent shell, that's why there's the `br` function. Assuming you use br, you could use this parameterization:

```
[[verbs]]
key = "ctrl-f"
execution = "cd {directory}"
from_shell = true
```

**Comment by NickyWeber** [comment] 2020-01-16 10:00
@Canop Thank you, works like a charm!

**Comment by pbuzdin** [comment] 2020-03-16 00:03
> @NickyWeber A `cd` must be done on the parent shell, that's why there's the `br` function. Assuming you use br, you could use this parameterization:
> 
> ```
> [[verbs]]
> key = "ctrl-f"
> execution = "cd {directory}"
> from_shell = true
> ```

@Canop is <kbd>Ctrl</kbd>+<kbd>Enter</kbd> possible in broot (iTerm2 on Mac)?

**Comment by wincent** [comment] 2020-05-29 13:09
> `option` + `enter` on MacOS Terminal and iTerm need to be set up by users to work properly. Setting it to output `Esc+Enter` worked for me on iTerm2.
> 
> <img alt="image" width="642" src="https://user-images.githubusercontent.com/1908664/72085636-8e13d300-32fd-11ea-9052-2fcd6c1582b0.png">

This is a good workaround, but only as long as you don't need to use the option key to type "special" characters such as `é`, `ñ`, `ü`, or `€` etc. I'm afraid that makes it a bit of a deal-breaker for me; I'm going to look into using [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements) to remap *just* `option`+`enter` and nothing else, and only in the terminal, but that is a pretty invasive/complex workaround — ideally, it would be possible to map another combination for doing what `alt`+`enter` does.

**Comment by Canop** [comment] 2020-05-29 13:32
You can map another combination. The verb is `:open_leave` (the counterpart is `:open_stay`):

```toml
[[verbs]]
key = "ctrl-o"
execution = ":open_leave"
```

**Closed** 2020-07-01 13:02 UTC
Labels: bug

**Comment by thomas-mangin** [comment] 2021-03-18 12:12
Setting iTerm as follow does not require any change of configuration under broot:
- remapping iTerm.app "Toogle Full Screen" from command-enter to "control-command-F" using System Preferences->Keyboard->ShortCuts->App Shortcuts
- changing the hex code sent under iTerm Preferences->Profiles->Default->Keys and mapping 'command-return' to "Send Hex Codes: 0x1b 0x0d"

**Comment by webdev4422** [comment] 2023-11-09 11:15
> Setting iTerm as follow does not require any change of configuration under broot:
> 
> * remapping iTerm.app "Toogle Full Screen" from command-enter to "control-command-F" using System Preferences->Keyboard->ShortCuts->App Shortcuts
> * changing the hex code sent under iTerm Preferences->Profiles->Default->Keys and mapping 'command-return' to "Send Hex Codes: 0x1b 0x0d" (0x1b 0x0d if you using the cmd key as "alt", if you want to use the "option" key, the code needs to be 0x1b 0x0a)

Thanks. As for iTerm2 Build 3.4.22, macOS Sonoma 14.1 (Apple M1 SoC), shortcuts not available in "System Preferences". 

But only changing the hex code sent under iTerm2 **Settings -> Profiles -> "My Profile" -> Keys -> Key Mappings** remapping: `Command-Return` to `Send Hex Codes: 0x1b 0x0d` - works great. (**"0x1b 0x0d"** - if using **cmd** as **alt** or **"0x1b 0x0a"** if using **opt** as **alt**)
