### ISSUE TITLE
Unstage key used while nothing staged

### ISSUE THREAD

**Issue by usama8800** [Canop/broot#715] opened 2023-06-03 17:36 UTC
![](https://i.imgur.com/1vT89B6.png)

Steps to reproduce

**Step 1**: Have this in your verbs config
```
{
  key: alt-right
  execution: ":stage"
}
{
  key: alt-left
  execution: ":unstage"
}
```

**Step 2**: Stage something (staging panel shows up)
**Step 3**: Switch to staging panel
**Step 4**: Repeat unstage key even after nothing is staged

**Comment by Canop** [comment] 2023-08-17 05:34
I can't reproduce because unstaging needs a selection.
Can you reproduce and provide the [debug log](https://dystroy.org/broot/community/#log) ?

**Comment by Canop** [comment] 2023-09-23 09:04
Closing because of lack of answer. Reopen if you just forgot.

**Closed by Canop** 2023-09-23 09:04 UTC
Labels: bug
