### ISSUE TITLE
on Windows pressing the shift key results on keypresses being ignored

### ISSUE THREAD

**Issue by sigfriedmcwild** [Canop/broot#176] opened 2020-01-22 07:08 UTC
On Windows, when the shift key is pressed input seems to be ignored by broot.

For example, pressing `'/'` works correctly, but pressing `shift` + `'/'` results in no input instead of `'?'`

broot 0.12.0 built with rustc 1.40.0 on Windows

**Comment by TimonPost** [comment] 2020-01-31 18:16
This happens with: SHIFT + ( /,  .,  ;) and all the numeric keys. 

Keys get different meanings when we press SHIFT and a key. For example `SHIFT + 0` will turn into the `)` character. `SHIFT + /` will result in the `?`. 

So while this is natural occurring, we may need to do something about this. When I press `SHIFT + /` I get the following event record:

```
KeyEventRecord { key_down: true, repeat_count: 1, virtual_key_code: 191, virtual_scan_code: 53, u_char: 63, control_key_state: ControlKeyState(48) }
```

Over at Microsoft: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes see the list of key codes. If we look up `191` (0XBF) we see: 

![image](https://user-images.githubusercontent.com/19969910/73563583-fae23f00-445d-11ea-9415-8349a5907e54.png)

So those key codes can tell us whether we have those special keys. Currently, crossterm takes the character that this key combination causes. But maybe this should be another entry in the `KeyCode` enum?

**Comment by graphixillusion** [comment] 2020-02-04 12:35
This problem is even more annoying with non english layouts: i have an italian keyboard and i must do "shift+." to display ":". I even tried with alt+58 or with on screen keyboard but still nothing.

**Comment by Canop** [comment] 2020-02-04 13:09
@graphixillusion We'll try to fix the problem but in the meantime you should use a space instead of `:`. In fact the space key is most usually the easiest to hit and the main reason commands are always displayed with a `: ` is for readability of the documentation.

**Comment by kscheel** [comment] 2020-02-22 11:13
I almost gave up after trying broot for a few minutes because of this. Makes it really hard to get into broot when you're new to it.

I was able to produce shifted / upper case characters by toggling caps-lock on and off. But every caps-lock toggle somehow also produces a space character.

I think this bug might scare away a lot of people who want to try out broot on Windows. I'll give it another shot now that I learned I can also use space instead of the colon :)

**Comment by Canop** [comment] 2020-02-22 12:19
@kscheel You're right. I hope it will be solved soon. In the meantime I've added a note in the installation page: https://dystroy.org/broot/documentation/installation/

**Comment by kscheel** [comment] 2020-02-22 12:35
> @kscheel You're right. I hope it will be solved soon. In the meantime I've added a note in the installation page: https://dystroy.org/broot/documentation/installation/

that's a good idea 👍 But a `:` is a colon, not a semicolon which is `;`

**Comment by Canop** [comment] 2020-02-22 12:38
@kscheel Ahaha... I'll never get it right on first try. Fixed now. Good thing I hadn't committed yet.

**Comment by Canop** [comment] 2020-06-20 17:10
It should be solved now but I can't test on windows.

**Comment by graphixillusion** [comment] 2020-06-20 19:14
@Canop i can confirm it: it works.

**Comment by Canop** [comment] 2020-06-20 19:15
@graphixillusion Thansk a lot

**Closed by Canop** 2020-06-20 19:15 UTC
Labels: bug, windows

**Comment by sigfriedmcwild** [comment] 2020-06-20 19:38
Can confirm it work too, thanks for the fix
