### ISSUE TITLE
Terminal not cleared at exit (with vim)

### ISSUE THREAD

**Issue by Pofilo** [Canop/broot#158] opened 2020-01-14 08:53 UTC
**Describe the bug**
When I quit broot, the terminal is not cleared.

**To Reproduce**
Here is my conf for enter and edit (with `export EDITOR=vim`):
```
[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "$EDITOR {file}"
leave_broot = false
```
Launch broot, open a file with enter (it is opened in vim), quit vim, quit broot.

**Expected behavior**
Broot is terminated successfully and the prompt is clean

**Screenshots**
If I don't open a file (I hide all the upper part of broot):
![image](https://user-images.githubusercontent.com/7527594/72328222-d131c580-36b2-11ea-8387-c2ad00d56282.png)

If I open a file:
![image](https://user-images.githubusercontent.com/7527594/72328068-8a43d000-36b2-11ea-919e-60de4e4c4f0a.png)

**Configuration (please complete the following information):**
 - OS: Debian 10 (64 bits), Raspbian (ARM) and CentOS 6 (32 bits)
 - Version: broot 0.11.8
 - Relevant configuration items (described in *to reproduce*).

**Additional context**
Maybe my verb is not configured as it should be but I *want* broot to be still opened when I exit vim.

**Comment by Canop** [comment] 2020-01-14 08:59
Right now, broot can't stay open in the same terminal with vim running (there are issues for trying to handle this).

If you want broot to stay open, then you must launch vi in a new terminal. The easiest solution for this is to configure your system opener (probably xdg-open) to open text files in vim.

**Comment by Canop** [comment] 2020-01-17 08:53
@Pofilo Do you agree this issue is a duplicate of https://github.com/Canop/broot/issues/38 ?

**Comment by Pofilo** [comment] 2020-01-18 11:57
No I don't think so. 
#158 is more about opening the editor in the same terminal than broot
#38 is more about opening the editor in another editor right ?

**Closed** 2020-06-23 16:23 UTC
