### ISSUE TITLE
Add detection/launcher for Powershell

### ISSUE THREAD

**Issue by stinos** [Canop/broot#159] opened 2020-01-14 11:20 UTC
In general it would be great if broot could detect which shell/environment it is running and install a suitable launcher; this issue in particular is for Powershell. Launchers have already been suggested in other issues, here's one take:

```
function br {
    $tempFile = New-TemporaryFile
    try {
        $broot = $env:BROOT
        if (-not $broot) {
             $broot = 'broot'
        }
        & $broot --outcmd $tempFile $args
        if ($LASTEXITCODE -ne 0) {
            Write-Error "$broot exited with code $LASTEXITCODE"
            return
        }
        $command = Get-Content $tempFile
        if ($command) {
            # broot returns extended-length paths but not all PowerShell/Windows
            # versions might handle this so strip the '\\?'
            Invoke-Expression $command.Replace("\\?\", "")
        }
    } finally {
        Remove-Item -force $tempFile
    }
}

$isDotSourced = $MyInvocation.InvocationName -eq '.' -or $MyInvocation.Line -eq ''
if (-not $isDotSourced) {
    br $args
}
```

- works as a script so if this gets saved as br.ps1 somewhere, users can choose how they want to use it (dot-source it, or add path to file to the PATH or ...)
- uses environment variable so users can set the path to the broot executable if broot isn't in the path for instance, or when developing and switching between versions etc. Defaults to broot instead of broot.exe so that it automatically works on pwsh on linux as well (tested on ubuntu 18.04)

**Comment by Canop** [comment] 2020-01-14 11:23
broot detects some shells, but not powershell, because I can't test that.

I'd need some win10 rust developer to try adapt what is done for fish: https://github.com/Canop/broot/blob/master/src/shell_install/fish.rs#L94

**Comment by PDQDakota** [comment] 2020-01-15 16:05
@Canop If it helps PowerShell is open source and cross platform. https://github.com/PowerShell/PowerShell#get-powershell

**Comment by Canop** [comment] 2020-01-15 16:09
@PDQDakota  Thanks, I didn't knew. It seems it's not the same version which is released with Windows, if I correctly understand the readme. And installing this on linux would probably not lead to the typical installation I want to detect.
Moreover, I don't have the time to learn this shell, so I'd like a Rust Windows developer to look at this.

**Comment by GrosSacASac** [comment] 2020-02-04 13:50
Last time I tried, I compiled broot with the rust compiler then used the full path to the compiled broot inside powershell

**Comment by pshirshov** [comment] 2020-09-21 15:19
PowerShell Core works fine on MacOS and Linux. It would be really great if you add support for it.

**Comment by Canop** [comment] 2020-09-21 15:24
I lack time to study powershell at the moment, even on linux, so I'd need help for this.

**Comment by thisismygitrepo** [comment] 2022-10-04 21:10
I can confirm the script works like a dream with latest version.

**Comment by adamency** [comment] 2023-02-01 03:20
Script works perfectly indeed.

PS: I strongly suggest putting it in your `$profile` as is, instead of the clunky way it is done by `broot` which creates a file and needs to modify your path for such a small added feature.

**Comment by AeliusSaionji** [comment] 2024-07-07 19:21
Looks like this one can be closed now?

**Closed** 2024-07-24 09:07 UTC
Labels: help wanted, windows
