### ISSUE TITLE
Fish detection is broken

### ISSUE THREAD

**Issue by masukomi** [Canop/broot#101] opened 2020-01-09 16:40 UTC
**Is everything clear?**
no response in the time i was willing to wait around....

**Describe the bug**
doesn't seem to be aware that i'm using fish shell. Just installed a bunch of bash stuff as if that was useful. 

**To Reproduce**
Steps to reproduce the behavior.

install fish with homebrew on macos (not sure if this is relevant or not) 

run `cargo install broot` 
run `broot`

**Expected behavior**
it would either install fish functions or tell me that fish wasn't supported. I expect it to definitely NOT install bash functions without asking.

**Screenshots**
```
$ broot

Broot should be launched using a shell function (see https://github.com/Canop/broot
for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
Y
Writing br shell function in /Users/masukomi/Library/Application Support/org.dystroy.broot/launcher/bash/1.
Creating link from /Users/masukomi/Library/Preferences/org.dystroy.broot/launcher/bash/br to /Users/masukomi/Library/Application Support/org.dystroy.broot/launcher/bash/1.
/Users/masukomi/.bashrc successfully patched, you can make the function immediately
available with
source /Users/masukomi/.bashrc

The br function has been installed.
You may have to restart your shell or source your shell init files.
Afterwards, you should start broot with br in order to use its full power.
```

**Configuration (please complete the following information):**
 - OS: macos v10.14.6
 - Version: 0.11.3
- Relevant configuration items

**Comment by Canop** [comment] 2020-01-09 16:44
I just merged a pull request fixing fish detection on Mac (fish doesn't use the standard mac location for config).

I'll deploy a new release for that soon.

**Comment by Canop** [comment] 2020-01-09 17:17
I just deployed the 0.11.4 which should fix this.

**Comment by squarism** [comment] 2020-01-09 17:46
Fish doesn't use the standard mac location but usually uses XDG which I think is aligned with broot's preference for XDG paths?  Installing from homebrew uses `~/Library/Preferences/org.dystroy.broot` where all my fish things are in `~/.config`.  I looked at the homebrew formula and don't see anything obvious that is configuring the path. 
 Is `~/.config/broot` the default?  If I install via cargo is that the default configuration path?

**Comment by Canop** [comment] 2020-01-09 17:48
@squarism I just deployed the 0.11.4 of broot which uses ~/.config for fish even on mac but I have no control of the homebrew formula and I don't think it's up to date (I have no mac and no specific knowledge)

**Comment by squarism** [comment] 2020-01-09 21:28
I installed 0.11.4 and it behaves differently now.  It detects fish.  But it does some things maybe not "right".  Here is my post install manual fixes/cleanup:

1. edit `.bash_profile`, remove line added
2. I moved `~/Library/Application\ Support/org.dystroy.broot/launcher/fish/1.fish` to `~/.config/fish/conf.d/br.fish`.  I don't know what the advantage here with a symlink is since the `~/Library` is a write-once, can't update kind of path too.  If the intention is to have a file that updates on broot upgrades, I don't know 
3. It still uses a non XDG path.  I installed from cargo.  It's coming from the directories crate.  I'll see if I can manage an improvement/contribution.

**Comment by Canop** [comment] 2020-01-10 07:19
Thanks for this observation. It's a little complicated to make a thing which works for several shells (especially the ones I don't personally use) and broot already has some "legacy" behaviors to avoid losing previous configurations. Most of the fish thing was made in the urgency and there should be a new proper specification to ensure it's fine (including for mac users).

**Comment by c02y** [comment] 2020-02-18 14:24
I download broot binary using "https://dystroy.org/broot/download/x86_64-linux/broot" from https://dystroy.org/broot/documentation/installation/ page

~~~
>> broot  # fish shell

Broot should be launched using a shell function (see https://github.com/Canop/broot for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
^C⏎                                                                                                                                                                                                                       >> bash
[chz@chz-pc bin]$ broot

Broot should be launched using a shell function (see https://github.com/Canop/broot for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
^C
[chz@chz-pc bin]$ ^C
[chz@chz-pc bin]$ exit^C
[chz@chz-pc bin]$
~~~

**Comment by Canop** [comment] 2020-02-18 14:28
@c02y I don't understand what you mean. Did you do a ctrl-c ? what's the # in the first line ?
Maybe come to https://miaou.dystroy.org/3490?broot ?

**Comment by c02y** [comment] 2020-02-18 14:33
Of cause I hit [Ctrl-c] to quit the command

The `#` is the comment, means I'm using fish shell at that time, then I switch to bash shell, it is the same result.

I tried to install broot using pacman package manager for Manjaro, it does't work either, no matter I'm using bash shell or fish shell.

**Comment by Canop** [comment] 2020-02-18 14:37
What did you answer when broot asks whether it can install the br function ?

**Comment by c02y** [comment] 2020-02-18 15:08
Really? I quit the command, I didn't saw this part in README, I thought something is wrong with it.

---------
UPDATE:

I just hit Y to install, and it works OK now.

Let me play with it for a while in case I post any other stupid questions again.

**Comment by Canop** [comment] 2020-02-18 15:11
@c02y You confirmed what I thought: that the *"The function is either missing, old or badly installed."* message gives a bad feeling that broot is broken. I must find a better and more positive way to do tell the same thing.

**Comment by c02y** [comment] 2020-02-18 16:08
You can add this part in README when new users start to use broot

**Closed** 2020-07-01 12:49 UTC
