### ISSUE TITLE
up/down arrow keys do nothing.

### ISSUE THREAD

**Issue by dan-da** [Canop/broot#168] opened 2020-01-18 07:53 UTC
I just installed broot for the first time with 'cargo install broot' on ubuntu linux 16.04 using bash.

**To Reproduce**
After invoking `br ~`, I see a directory tree, but navigation keys such as up/down arrow and pg up/down do nothing.

**Expected behavior**
upon pressing down arrow or up arrow, the selected line should move down or up accordingly.

**Comment by Canop** [comment] 2020-01-18 09:14
As this isn't the normal behavior, I'd need some information.

Can you please follow this procedure ?
* launch broot with `BROOT_LOG=debug br ~`
* hit the down arrow key
* quit broot
* paste here the content of the `dev.log` file

**Comment by dan-da** [comment] 2020-01-18 22:52
done, here ya go.  seems no KeyEvent for down arrow key when I pressed it... 

```
22:50:41 [ INFO] Starting Broot v0.11.9 with log level DEBUG
22:50:41 [DEBUG] (1) broot::shell_install: Shell script already installed. Doing nothing.
22:50:41 [DEBUG] (1) broot::app: we're on screen
22:50:41 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=None
22:50:41 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 32 lines for a goal of 31
22:50:41 [DEBUG] (1) broot::flat_tree: turning "/home/danda/background.png" into Pruning
22:50:52 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Esc, modifiers: (empty) })
22:50:52 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: Back }
22:50:52 [DEBUG] (1) broot::app: action: Back
22:50:52 [DEBUG] (1) broot::app: quitting on last pop state
22:50:52 [DEBUG] (1) broot::app: we left the screen
22:50:52 [ INFO] bye
```

**Comment by dan-da** [comment] 2020-01-18 23:00
btw, that was running in Konsole terminal.    Just for kicks, I used to ctrl-alt-f1 to go to a linux text console, and re-ran the test.  This time, arrow keys pressed are noticed, but it only changes text in the status line and does not move selected line up/down.  Here is debug log for that.

```
22:54:44 [ INFO] Starting Broot v0.11.9 with log level DEBUG
22:54:44 [DEBUG] (1) broot::shell_install: Shell script already installed. Doing nothing.
22:54:44 [DEBUG] (1) broot::app: we're on screen
22:54:44 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=None
22:54:44 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 47 lines for a goal of 46
22:54:44 [DEBUG] (1) broot::flat_tree: turning "REDACTED" into Pruning
22:54:45 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Down, modifiers: (empty) })
22:54:45 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: VerbIndex(10) }
22:54:45 [DEBUG] (1) broot::app: action: VerbIndex(10)
22:54:47 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Esc, modifiers: (empty) })
22:54:47 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: Back }
22:54:47 [DEBUG] (1) broot::app: action: Back
22:54:47 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Esc, modifiers: (empty) })
22:54:47 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: Back }
22:54:47 [DEBUG] (1) broot::app: action: Back
22:54:47 [DEBUG] (1) broot::app: quitting on last pop state
22:54:47 [DEBUG] (1) broot::app: we left the screen
22:54:47 [ INFO] bye
```

**Comment by dan-da** [comment] 2020-01-18 23:04
weird.   now I just tried it again in Konsole, and it is working perfectly.  I even exited and restarted br several times and it works fine each time and with different directories.   So I have now idea what is going on, but I will post here if it happens again.

**Comment by dan-da** [comment] 2020-01-18 23:08
also, I think that in the linux text console, the arrow key is really working and that is why the status-bar text changes, but for some reason the background/foreground color of the selected line is not changing.  Perhaps due to TTY mode or whatever.  So that may be a separate issue you might want to look at.

**Comment by Canop** [comment] 2020-05-22 06:02
Due to lack of reproduction, I'm closing the issue. If it comes back, you may reopen.

**Closed by Canop** 2020-05-22 06:02 UTC

**Comment by aminya** [comment] 2021-06-30 10:17
I am also having the same issue. What was the solution? It happens rather randomly

**Comment by Canop** [comment] 2021-06-30 10:20
@aminya Can you please give me [the log](https://dystroy.org/broot/community/#log) exhibiting the problem ? If you can show the log (with tail -f) in another terminal while you use the arrow keys, I'd like to know if you can see the keys being received by broot.

If somebody isn't clear, don't hesitate to come to the chat: https://miaou.dystroy.org/3490

**Comment by aminya** [comment] 2021-06-30 10:25
Here is the log if I set `EDITOR="nvim"`. Note that I am `ssh`ing to a Mac VM, and that's why I was using a terminal editor.

```rs
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: broot.log
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 03:23:11.722 [INFO] cli_log::init: Starting broot v1.6.1 with log level DEBUG
   2   │ 03:23:11.725 [DEBUG] broot::cli: Conf::from_default_location() took 472.32µs
   3   │ 03:23:11.725 [DEBUG] broot::cli: config: Conf {
   4   │     files: [
   5   │         "/Users/amin/.config/broot/conf.hjson",
   6   │     ],
   7   │     default_flags: None,
   8   │     date_time_format: None,
   9   │     verbs: [
  10   │         VerbConf {
  11   │             invocation: Some(
  12   │                 "edit",
  13   │             ),
  14   │             internal: None,
  15   │             external: None,
  16   │             execution: Some(
  17   │                 String(
  18   │                     "$EDITOR +{line} {file}",
  19   │                 ),
  20   │             ),
  21   │             cmd: None,
  22   │             cmd_separator: None,
  23   │             key: None,
  24   │             keys: [],
  25   │             shortcut: Some(
  26   │                 "e",
  27   │             ),
  28   │             leave_broot: Some(
  29   │                 false,
  30   │             ),
  31   │             from_shell: None,
  32   │             apply_to: None,
  33   │             set_working_dir: None,
  34   │             working_dir: None,
  35   │             description: None,
  36   │             auto_exec: None,
  37   │         },
  38   │         VerbConf {
  39   │             invocation: Some(
  40   │                 "create {subpath}",
  41   │             ),
  42   │             internal: None,
  43   │             external: None,
  44   │             execution: Some(
  45   │                 String(
  46   │                     "$EDITOR {directory}/{subpath}",
  47   │                 ),
  48   │             ),
  49   │             cmd: None,
  50   │             cmd_separator: None,
  51   │             key: None,
  52   │             keys: [],
  53   │             shortcut: None,
  54   │             leave_broot: Some(
  55   │                 false,
  56   │             ),
  57   │             from_shell: None,
  58   │             apply_to: None,
  59   │             set_working_dir: None,
  60   │             working_dir: None,
  61   │             description: None,
  62   │             auto_exec: None,
  63   │         },
  64   │         VerbConf {
  65   │             invocation: Some(
  66   │                 "git_diff",
  67   │             ),
  68   │             internal: None,
  69   │             external: None,
  70   │             execution: Some(
  71   │                 String(
  72   │                     "git difftool -y {file}",
  73   │                 ),
  74   │             ),
  75   │             cmd: None,
  76   │             cmd_separator: None,
  77   │             key: None,
  78   │             keys: [],
  79   │             shortcut: Some(
  80   │                 "gd",
  81   │             ),
  82   │             leave_broot: Some(
  83   │                 false,
  84   │             ),
  85   │             from_shell: None,
  86   │             apply_to: None,
  87   │             set_working_dir: None,
  88   │             working_dir: None,
  89   │             description: None,
  90   │             auto_exec: None,
  91   │         },
  92   │         VerbConf {
  93   │             invocation: Some(
  94   │                 "backup {version}",
  95   │             ),
  96   │             internal: None,
  97   │             external: None,
  98   │             execution: Some(
  99   │                 String(
 100   │                     "cp -r {file} {parent}/{file-stem}-{version}{file-dot-extension}",
 101   │                 ),
 102   │             ),
 103   │             cmd: None,
 104   │             cmd_separator: None,
 105   │             key: Some(
 106   │                 "ctrl-b",
 107   │             ),
 108   │             keys: [],
 109   │             shortcut: None,
 110   │             leave_broot: Some(
 111   │                 false,
 112   │             ),
 113   │             from_shell: None,
 114   │             apply_to: None,
 115   │             set_working_dir: None,
 116   │             working_dir: None,
 117   │             description: None,
 118   │             auto_exec: Some(
 119   │                 false,
 120   │             ),
 121   │         },
 122   │         VerbConf {
 123   │             invocation: Some(
 124   │                 "terminal",
 125   │             ),
 126   │             internal: None,
 127   │             external: None,
 128   │             execution: Some(
 129   │                 String(
 130   │                     "$SHELL",
 131   │                 ),
 132   │             ),
 133   │             cmd: None,
 134   │             cmd_separator: None,
 135   │             key: Some(
 136   │                 "ctrl-t",
 137   │             ),
 138   │             keys: [],
 139   │             shortcut: None,
 140   │             leave_broot: Some(
 141   │                 false,
 142   │             ),
 143   │             from_shell: None,
 144   │             apply_to: None,
 145   │             set_working_dir: Some(
 146   │                 true,
 147   │             ),
 148   │             working_dir: None,
 149   │             description: None,
 150   │             auto_exec: None,
 151   │         },
 152   │     ],
 153   │     skin: None,
 154   │     special_paths: {},
 155   │     search_modes: None,
 156   │     disable_mouse_capture: None,
 157   │     cols_order: None,
 158   │     show_selection_mark: Some(
 159   │         true,
 160   │     ),
 161   │     ext_colors: {},
 162   │     syntax_theme: None,
 163   │     true_colors: None,
 164   │     icon_theme: None,
 165   │     modal: None,
 166   │     max_panels_count: None,
 167   │     quit_on_last_cancel: None,
 168   │     file_sum_threads_count: None,
 169   │ }
 170   │ 03:23:11.741 [DEBUG] broot::tree_build::builder: GitIgnorer::default() took 104ns
 171   │ 03:23:11.754 [DEBUG] broot::app::app: display panel took 1.440876ms
 172   │ 03:23:11.756 [INFO] broot::app::app: pending_tasks took 946ns
 173   │ 03:23:13.946 [INFO] broot::app::app: event: Key(KeyEvent { code: Esc, modifiers: NONE })
 174   │ 03:23:13.948 [DEBUG] broot::app::app: command after add_event: Internal { internal: back, input_invocation: None }
 175   │ 03:23:13.953 [DEBUG] broot::app::app: display panel took 4.208174ms
 176   │ 03:23:13.954 [INFO] broot::app::app: pending_tasks took 1.454µs
 177   │ 03:23:14.889 [INFO] broot::app::app: event: Key(KeyEvent { code: Char(':'), modifiers: NONE })
 178   │ 03:23:14.890 [DEBUG] broot::app::app: command after add_event: VerbEdit(VerbInvocation { name: "", args: None, bang: false })
 179   │ 03:23:14.897 [DEBUG] broot::app::app: display panel took 5.846348ms
 180   │ 03:23:14.898 [INFO] broot::app::app: pending_tasks took 717ns
 181   │ 03:23:15.072 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('q'), modifiers: NONE })
 182   │ 03:23:15.073 [DEBUG] broot::app::app: command after add_event: VerbEdit(VerbInvocation { name: "q", args: None, bang: false })
 183   │ 03:23:15.079 [DEBUG] broot::app::app: display panel took 4.933129ms
 184   │ 03:23:15.081 [INFO] broot::app::app: pending_tasks took 1.255µs
 185   │ 03:23:15.322 [INFO] broot::app::app: event: Key(KeyEvent { code: Enter, modifiers: NONE })
 186   │ 03:23:15.323 [DEBUG] broot::app::app: command after add_event: VerbInvocate(VerbInvocation { name: "q", args: None, bang: false })
 187   │ 03:23:15.325 [DEBUG] broot::task_sync: dead dam
 188   │ 03:23:15.328 [INFO] broot: bye
```

**Comment by Canop** [comment] 2021-06-30 10:33
So none of the arrow key presses comes til broot. Either the terminal (or multiplexer or VM OS or whatever) is filtering them. So there's not much broot can do there.

Can you please give more details about all the sofware+version involved ? Can you try with another terminal ?

**Comment by aminya** [comment] 2021-06-30 10:40
Using the Mac VM directly inside its terminal app (zsh or bash) doesn't have the same issue. This seems to happen only with SSHing. 

I am using [Sosumi](https://github.com/popey/sosumi-snap/), and I have sshed using [this method](https://github.com/foxlet/macOS-Simple-KVM/issues/185#issuecomment-870270109).

Other versions:
```
> broot --version
broot 1.6.1

> nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3

> mcfly --version
McFly 0.5.7
```

**Comment by aminya** [comment] 2021-06-30 10:44
Another interesting fact. Setting `editor=nano` doesn't have the same issue as `nvim`

**Comment by Canop** [comment] 2021-06-30 10:49
I don't understand why you mention the editor. Are you launching the terminal from neovim ?

**Comment by aminya** [comment] 2021-06-30 10:51
No, I directly run broot, but that seems to be the issue with the EDITOR env variable!

**Comment by aminya** [comment] 2021-06-30 10:55
Or maybe the issue is with mcfly that breaks broot. I think because I used `mcfly` to source my bash profile. 

There is some conflict happening here.

**Comment by aminya** [comment] 2021-06-30 10:59
There are two interestingly related issues:
https://github.com/cantino/mcfly/issues/108
https://github.com/cantino/mcfly/issues/83

**Comment by SkyWriter** [comment] 2022-11-07 16:23
Necroposting here, but want to add my 2 cents, so that others bang their heads against the wall a little less.

In my case dropping `zle -N zle-line-finish` from my .zshrc file remedied broot up and down keys not working.

**Comment by tombh** [comment] 2023-06-03 15:54
Just another datapoint. Changing `EDITOR=nvim` to `EDITOR=vi` fixes arrow keys for me too. And I don't use `mcfly`.
