### ISSUE TITLE
Configurable fuzzy filter precision (at least 2 consequent characters)

### ISSUE THREAD

**Issue by xRoker** [Canop/broot#356] opened 2021-03-04 01:47 UTC
Like some other folks here, I use broot as a file selector (fuzzy path search mode, e.g. p/) and love it!
I noticed one small annoyance when working with larger, deeply nested codebases.

The likelihood of matching at least one character in a certain order is much higher on longer paths:
e.g. searching for "storetypes", will also yield Que**st**i**o**nCard/pr**e**viewers/common/**types** and similar results.

This creates a lot of noise in the output and makes it harder to find what I'm looking for. It would be very helpful to be able to limit matching to at least 2 consequent characters.

**Comment by Canop** [comment] 2021-03-04 06:09
I'm not fond of user configuration here because it's hard to do properly but the fuzzy finder rules clearly needs some tuning, and the specific rule you're mentioning makes sense.

If you want to test yourself and are willing to compile broot, here's where it is: https://github.com/Canop/broot/blob/master/src/pattern/fuzzy_pattern.rs#L11

If you don't, I'll experiment myself with this change.

**Comment by xRoker** [comment] 2021-03-04 07:02
@Canop I'll give it a shot this weekend.
I'm sorry, I'm not familiar with the algorithm used here. Your link points to line 11. Do I understand correctly that it's possible to achieve this by simply adjusting the scores? By briefly looking, I've got the impression that we might need to adjust `score_n_chars` (L271). I'd appreciate a bit more detail on where to look. Thank you!

**Comment by Canop** [comment] 2021-03-04 10:04
Sorry, I just had a look again at that code and it's really not easy to do. I'll make a preliminary change in a specific branch so that we can experiment.

**Comment by Canop** [comment] 2021-03-04 10:27
The current core algorithm should be improved before doing this tuning. Right now it would see **first**xxx**p**xxxp**art** instead of **first**xxxpxxx**part** . It's fundamentally quite easy but the problem is always the performances. I'll dive into this as soon as possible.

**Comment by Canop** [comment] 2021-03-05 14:45
I've pushed a new branch, "fuzzy-experiment", where

- it's easier to play with the matching code
- simple cases of singled chars are avoided
- singled chars receive a malus in scoring

In this picture the old matching (left) and the new (one):

![image](https://user-images.githubusercontent.com/617006/110126316-98781280-7dc4-11eb-816e-9537b9fbc6aa.png)

**Comment by xRoker** [comment] 2021-03-07 21:41
@Canop the simplified code in the branch is way easier to reason about, thank you!

I noticed there is one case that is currently not handled: for the pattern `ABC` the result is xxx**AB**xxxxAB**C**xxx and not xxxABxxxx**ABC**xxx.
I wrote a function that checks the final `pos` vector for singles, and if a single is found, `match_starting_at_index` returns no match. But with this case, it obviously doesn't work.
Any thoughts if this case is possible to fix?

**Comment by Canop** [comment] 2021-03-08 06:15
The case you mention should not happen and I don't reproduce it:
![image](https://user-images.githubusercontent.com/617006/110281974-f6337700-7fdd-11eb-8a93-223c0562c536.png)

I guess separators, or case, play a role in the real names you observed. What was the exact file name ? Can you make a screenshot ?

**Comment by xRoker** [comment] 2021-03-08 15:53
@Canop yep, here it is: 
![Image 2021-03-08 at 7 51 43 AM](https://user-images.githubusercontent.com/8567013/110345293-42cd8100-7fe3-11eb-88da-86f952aa0d15.jpg)
Notice split of "typings"

**Comment by Canop** [comment] 2021-03-08 15:59
Ok, this one is different, just due to the fact it's hard to test all possible combinations fast enough.

**Comment by Canop** [comment] 2021-03-10 17:40
I've made other changes which minimize the number of holes.
And I've merged it into master. Unless I find bugs it should be in next release.

Here's how adding one letter now moves the matched group:
![image](https://user-images.githubusercontent.com/617006/110672521-ff843580-81cf-11eb-88a7-0eccd99a7009.png)

**Comment by xRoker** [comment] 2021-03-15 04:09
@Canop sweet! The grouping works beautifully!
It seems like the calculation of singled chars doesn't cover all the cases (src/pattern/fuzzy_pattern.rs - lines 122-124). Currently, it just checks if the current char in the loop is part of the previous group. Yet, it doesn't cover the case when the char is a part of the next group.
Please take a look if my approach makes sense:
```rust
fn count_singles(pos: &[usize], cand_len: usize) -> usize {
    let mut count = 0;
    // Number of characters in the current group
    let mut streak = 0;
    let mut prev = pos[0];
    for i in 1..pos.len() {
        let curr = pos[i];
        if curr > prev + 1 {
            // If no current group, or this is the last matched character but not the last in the candidate.
            if streak == 0 || (i == (pos.len() - 1) && curr < cand_len) {
                count += 1;
            } else {
                // Reset the streak, this char can be a beginning of a new group.
                streak = 0;
            }
        } else {
            streak += 1;
        }
        prev = curr;
    }
    return count;
}
```

**Comment by Canop** [comment] 2021-03-15 06:06
> Yet, it doesn't cover the case when the char is a part of the next group.

I don't understand this. It' part of the algorithm if I understand your question. Do you have cases of sub-opbtimal groups related to this ?


> Please take a look if my approach makes sense.

Please before submitting code tell me whether you applied the tests (with cargo test) and compare (with cargo bench) the performances with the previous version.

It's often easier to come and [chat on miaou](https://miaou.dystroy.org/3490).

**Closed** 2021-04-27 16:06 UTC
