### ISSUE TITLE
size mode (:s) blocks

### ISSUE THREAD

**Issue by extrawurst** [Canop/broot#174] opened 2020-01-21 21:04 UTC
**Describe the bug**
> broot is fast and never blocks
I must say broot is really fast! Good work!

*But* in size-mode `:s` it hangs for super long even though it is documented to be measuring sizes in background. see the gif showing the issue clearly.

**To Reproduce**
Have a 100GB folder size (in total) and see how this is handled by broot in the video

**Expected behavior**
size mode should not block me from making *any* input, essentially not block the user interface.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/776816/72842847-9115a880-3c99-11ea-87a3-2cd10eb3a4d6.gif)

*Note* that I keep pressing `arrow down` the entire time after switching to size mode `:s`
On the lower right there is a timer. 
After `0:02s` it is impossible to do any input until `0:11s`

**Configuration (please complete the following information):**
- OS: Mac OS 10.14.6 (18G103)
- ZSH shell in term2

**Comment by Canop** [comment] 2020-01-21 21:05
Hum... Can you precise what version of broot you have ?

**Comment by Extrawurst** [comment] 2020-01-21 21:06
Sure, I just installed it using home-brew: `broot 0.12.0`

**Comment by Canop** [comment] 2020-01-21 21:10
I definitely can't reproduce this problem (but I have no real slow disk available which could block the CPU). I'd like other people, especially on Mac, to tell me whether they observe this.

**Comment by Extrawurst** [comment] 2020-01-21 21:17
not sure how slow of a disk you talk but its a macbook from 2018 (SSD, multicore) but would guesstimate that it should be able to handle a few worker threads waiting for IO and a main thread keeping the UI responsive :P

maybe its some caching that you do right on br startup that in my repro is not done yet cause I also just star br right when switching into  space mode in this *massive* folder?

**Comment by Canop** [comment] 2020-01-21 21:20
That's not a caching problem. I tested on my biggest disks with no cache. Maybe the OS which does some cache. But having other people with a mac and a big disk  confirm or not the problem would already be interesting (but I must confess I have no lead right now).

**Comment by Canop** [comment] 2020-06-20 17:13
Other people comments on this would help. Do other people observe this ?

**Comment by Canop** [comment] 2020-07-01 11:13
Size computation has been rewritten, and I've got no confirmation. Closing.

Note that if you have mounted a *very* slow device (for example a remote one) you may exclude it from automatic enter with

```
[special-paths]
"/media/slow-backup-disk" = "no-enter"
```

**Closed by Canop** 2020-07-01 11:13 UTC
